[2022-01-04 23:38:31,482] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop scheduled__2022-01-04T00:00:00+00:00 [queued]>
[2022-01-04 23:38:31,504] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop scheduled__2022-01-04T00:00:00+00:00 [queued]>
[2022-01-04 23:38:31,505] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-04 23:38:31,505] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-04 23:38:31,505] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-04 23:38:31,612] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): run_after_loop> on 2022-01-04 00:00:00+00:00
[2022-01-04 23:38:31,615] {standard_task_runner.py:52} INFO - Started process 11513 to run task
[2022-01-04 23:38:31,621] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'run_after_loop', 'scheduled__2022-01-04T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', '/home/rhavel/Documentos/DEPLOY-PROJECTS/first-airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmp21o8ptcv', '--error-file', '/tmp/tmp6_o45dfc']
[2022-01-04 23:38:31,622] {standard_task_runner.py:77} INFO - Job 11: Subtask run_after_loop
[2022-01-04 23:38:31,762] {logging_mixin.py:109} INFO - Running <TaskInstance: example_bash_operator.run_after_loop scheduled__2022-01-04T00:00:00+00:00 [running]> on host rhavel-VPCEG13EB
[2022-01-04 23:38:32,031] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=run_after_loop
AIRFLOW_CTX_EXECUTION_DATE=2022-01-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-04T00:00:00+00:00
[2022-01-04 23:38:32,034] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-04 23:38:32,035] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo 1']
[2022-01-04 23:38:32,065] {subprocess.py:85} INFO - Output:
[2022-01-04 23:38:32,066] {subprocess.py:89} INFO - 1
[2022-01-04 23:38:32,067] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-04 23:38:32,283] {taskinstance.py:1267} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=run_after_loop, execution_date=20220104T000000, start_date=20220105T023831, end_date=20220105T023832
[2022-01-04 23:38:32,396] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-04 23:38:32,426] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
